version: "3.4"

services:
  app:
    image: strm/helloworld-http

  nginx:
    build: ./nginx
    volumes:
      - nginx_log_volume:/var/log/nginx/
    ports: 
      - ${HOST_MACHINE_PORT}:80

  nginx-exporter:
    build: ./nginx-exporter
    volumes:
      - nginx_log_volume:/var/log/nginx/

volumes:
  nginx_log_volume:
